# base svd model path
base_model_path: stabilityai/stable-video-diffusion-img2vid-xt-1-1

# checkpoint path
#ckpt_path: models/MimicMotion_1-1.pth # 72帧用这个模型 用这个模型使用num_frames: 16 效果比  MimicMotion_1-1.pth 差
ckpt_path: models/MimicMotion_1.pth

test_case:
  - ref_video_path: assets/example_data/videos/pose1.mp4
    ref_image_path: assets/example_data/images/demo1.jpg
    # tile_size @ pipeline_mimicmotion.py
    num_frames: 4
    resolution: 576
    # tile_overlap  @ pipeline_mimicmotion.py
    frames_overlap: 2
    num_inference_steps: 25
    noise_aug_strength: 0
    guidance_scale: 2.0
    sample_stride: 2
    fps: 15
    seed: 42


 